version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - 3306:3306
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=eyrafmzx_urcdipco
      - MARIADB_DATABASE=eyrafmzx_dbapi33pro
  myapp:
    image: php:7.2.33-apache
    command:
      - bash
      - -c
      - |
        docker-php-ext-install mysqli
        docker-php-ext-enable mysqli
        a2enmod rewrite
        echo 'PassEnv CI_ENV' > /etc/apache2/conf-enabled/expose-env.conf
        apache2-foreground
    ports:
      - '8000:80'
    volumes:
      - './demo.api.nexosuite.com:/var/www/html/'
    environment:
      - CI_ENV=docker
    depends_on:
      - mariadb
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=mariadb
      - PMA_USER=eyrafmzx_urcdipco
    depends_on:
      - mariadb
