on: push
name: Build and Publish Front End Framework Website
jobs:
  Angular-Build-Action:
    name: Angular-Build-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: |
          npm install
          npm run build
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "docs/.htaccess"
          target: "dist/.htaccess"
      - uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftp
          port: 21
          dangerous-clean-slate: true
          server_dir: /
          local-dir: /home/runner/work/angular-codeigniter-blog/angular-codeigniter-blog/dist/
          
